apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c902c1xzu-go
  janus-idp.io/tekton: c902c1xzu-go
  backstage.io/kubernetes-id: c902c1xzu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c902c1xzu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
